###

# curl --request GET
#  --url http://path_to_your_api/
#  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Imd6SmxBY2VfNTN0SEVwMU9pT2JNeCJ9.eyJpc3MiOiJodHRwczovL2Rldi1qemFyOGZ5d25oZHV6ZTYyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJWeVI4Y2NvaVdqYXFLYW5WZktXclc2MEhBY0dZUVdPS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9kZXYtanphcjhmeXduaGR1emU2Mi51cy5hdXRoMC5jb20vYXBpL3YyLyIsImlhdCI6MTY4NjgwNzYwMSwiZXhwIjoxNjg2ODk0MDAxLCJhenAiOiJWeVI4Y2NvaVdqYXFLYW5WZktXclc2MEhBY0dZUVdPSyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.q1gYi3lyIMG4p-G6_sWYWKwfZ8YYb3J2rMhMV2WGy4k1_sMKzbrqZtJObtRhUEHwVT51C8Ced-5aZM5ZW1UWZmP_89Stw0aDTrGhAEKwgPyuOSt7NbdMn0r3VIu1Xs-czj50d_akEdp3fvn1-pFEPugWckEefmLO3zFJqvocsAn2VdtfBO4vdr-l-u5aE5qwT2z84XZhO7EuTd-8mddLSL5DSR72EExCnDuegLVmsFFt6ZUVDKBFR25qIb61fuxhIAZ1wmDXLuVrtYJTgeICqdwOMPgDLFOBWUIvpXRGAtnpePdFGcD4FBhmYZLwAFfxMWaxXRRjqF0eKuYkYDhmgQ'
GET http://localhost:8080/api/users
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Imd6SmxBY2VfNTN0SEVwMU9pT2JNeCJ9.eyJpc3MiOiJodHRwczovL2Rldi1qemFyOGZ5d25oZHV6ZTYyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJWeVI4Y2NvaVdqYXFLYW5WZktXclc2MEhBY0dZUVdPS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9kZXYtanphcjhmeXduaGR1emU2Mi51cy5hdXRoMC5jb20vYXBpL3YyLyIsImlhdCI6MTY4NjgwNzYwMSwiZXhwIjoxNjg2ODk0MDAxLCJhenAiOiJWeVI4Y2NvaVdqYXFLYW5WZktXclc2MEhBY0dZUVdPSyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.q1gYi3lyIMG4p-G6_sWYWKwfZ8YYb3J2rMhMV2WGy4k1_sMKzbrqZtJObtRhUEHwVT51C8Ced-5aZM5ZW1UWZmP_89Stw0aDTrGhAEKwgPyuOSt7NbdMn0r3VIu1Xs-czj50d_akEdp3fvn1-pFEPugWckEefmLO3zFJqvocsAn2VdtfBO4vdr-l-u5aE5qwT2z84XZhO7EuTd-8mddLSL5DSR72EExCnDuegLVmsFFt6ZUVDKBFR25qIb61fuxhIAZ1wmDXLuVrtYJTgeICqdwOMPgDLFOBWUIvpXRGAtnpePdFGcD4FBhmYZLwAFfxMWaxXRRjqF0eKuYkYDhmgQ

###

