version: '3'
services:
  postgres:
    container_name: auth0_axum
    build: image/postgres
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"